import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { apiClient } from "../api/client";
import { SiteHeader } from "../components/SiteHeader";
import { useAuthStore } from "../store/authStore";
type Theater = { id: string; name: string; city: string; address: string; screens: unknown[] };
export default function ClientDashboardPage() { const user = useAuthStore(s => s.user); const [profile, setProfile] = useState<any>(null); const [theaters, setTheaters] = useState<Theater[]>([]); const [message, setMessage] = useState(""); const [form, setForm] = useState({ name:"", city:"", address:"", description:"", totalScreens:"1" });
 const load = () => Promise.all([apiClient.get("/clients/me"), apiClient.get("/clients/me/theaters")]).then(([p,t]) => { setProfile(p.data.data); setTheaters(t.data.data); }).catch(e => setMessage(e.response?.data?.message ?? "Could not load partner details"));
 useEffect(() => { if (user?.role === "CLIENT") load(); }, [user?.role]); if (!user) return <Navigate to="/login" replace />; if (user.role !== "CLIENT") return <Navigate to="/movies" replace />;
 const create = async(e: React.FormEvent) => { e.preventDefault(); try { await apiClient.post("/theaters", { ...form, totalScreens:Number(form.totalScreens), amenities:[] }); setMessage("Theatre created. Add screens and showtimes from its management API."); setForm({ name:"", city:"", address:"", description:"", totalScreens:"1" }); load(); } catch(err:any) { setMessage(err.response?.data?.message ?? "Could not create theatre. Your partner account may still be awaiting approval."); } };
 return <div className="app-shell"><SiteHeader /><main className="page"><span className="eyebrow">Theatre partner</span><h1 className="title">{profile?.businessName || "Your cinema workspace"}</h1><p className="subtitle">{profile?.status === "APPROVED" ? "Your account is approved. Create venues, screens, and showtimes." : "Your partner application is being reviewed. You’ll be able to manage venues once approved."}</p>{message && <p className="error">{message}</p>}<div className="dashboard-grid"><section className="dashboard-card"><span className="eyebrow">Your venues</span><h2>{theaters.length} theatre{theaters.length === 1 ? "" : "s"}</h2><div className="admin-list">{theaters.length ? theaters.map(t => <article key={t.id}><div><b>{t.name}</b><span>{t.address}, {t.city} · {t.screens.length} screens</span></div></article>) : <p className="muted">Your venue list is empty.</p>}</div></section><section className="dashboard-card"><span className="eyebrow">Venue setup</span><h2>Add a theatre</h2><form className="admin-form" onSubmit={create}>{Object.entries({ name:"Theatre name", city:"City", address:"Address", description:"Description", totalScreens:"Number of screens" }).map(([key,label]) => <label key={key}>{label}<input required={key !== "description"} type={key === "totalScreens" ? "number" : "text"} min={key === "totalScreens" ? 1 : undefined} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="btn" disabled={profile?.status !== "APPROVED"}>Create theatre</button></form></section></div></main></div>;
}
